import React, { useEffect, useState } from "react";
import { BrainCircuit, ChevronDown, Globe2, Layers3, Menu, Mic, Orbit, Phone, Search, Send, Settings2, ShieldCheck, Sparkles, Smartphone, X, ImagePlus } from "lucide-react";
import ContactEarthPage from "./pages/ContactEarthPage";
import PhonePage from "./pages/PhonePage";
import DomainsPage from "./pages/DomainsPage";
import MobileDataPage from "./pages/MobileDataPage";
import AIPhotoEngineerPage from "./pages/AIPhotoEngineerPage";

const sections = [
  { id: "orbit", label: "Orbit", icon: Orbit, description: "3D Earth workspace and geographic visualization." },
  { id: "ai-mode", label: "AI command center", icon: BrainCircuit, description: "AI workspace, commands, and developer tools." },
  { id: "photo-engineer", label: "AI Photo Engineer", icon: ImagePlus, description: "Create and edit images from natural-language requests and image entries." },
  { id: "phone", label: "Phone / Civic", icon: Phone, description: "Contacts, communications, and civic directories." },
  { id: "mobile-data", label: "Mobile Data", icon: Smartphone, description: "Cell service and multiple device configuration." },
  { id: "domains", label: "Domains", icon: Globe2, description: "Domain registry, DNS, and domain management." },
  { id: "prosecutors", label: "Prosecutors", icon: ShieldCheck, description: "Prosecutor directory and civic resources." },
  { id: "courthouses", label: "Courthouses", icon: Layers3, description: "Federal courthouse directory and tools." },
  { id: "creative-projects", label: "Creative", icon: Sparkles, description: "Document, web, image, animation, audio, and video projects." },
  { id: "ledger-projects", label: "Ledger", icon: Layers3, description: "Ledger and financial workspace projects." },
];

function HomeBody({ navigate }: { navigate: (path: string) => void }) {
  const [prompt, setPrompt] = useState(""); const [submitted, setSubmitted] = useState(false);
  return <div className="min-h-screen bg-[#f6f2e9] text-[#19211e]"><section id="orbit" className="border-b border-[#17231e]/10 bg-[#122019] px-5 py-12 text-white sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="font-ledger text-[10px] uppercase tracking-[.22em] text-[#c9a84c]">Bonds Studio · Orbital workspace</p><h1 className="mt-3 max-w-3xl font-display text-4xl leading-tight sm:text-6xl">One studio for AI, phone, domains, civic, creative, and ledger work.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-[#d1d9d3]">The restored Studio shell keeps the Earth-centered workspace, full navigation, AI command box, Domains registry, and project body sections together in one responsive interface.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={() => navigate("/phone/earth")} className="inline-flex items-center gap-2 bg-[#c9a84c] px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#17231e]"><Globe2 size={15}/>Contact Earth</button><button onClick={() => navigate("/domains")} className="inline-flex items-center gap-2 border border-white/20 px-4 py-3 text-xs font-bold uppercase tracking-wider text-white"><Globe2 size={15}/>Domains</button></div></div><div className="relative mx-auto aspect-square w-full max-w-[430px] overflow-hidden rounded-full border border-white/10 bg-[radial-gradient(circle_at_35%_30%,#507d72,#173a35_42%,#061611_75%)] shadow-[0_30px_100px_rgba(0,0,0,.45)]"><div className="absolute inset-[8%] rounded-full border border-[#c9a84c]/30"/><div className="absolute inset-[18%] rounded-full border border-white/10"/><div className="absolute left-[28%] top-[25%] h-3 w-3 rounded-full bg-[#c9a84c]"/><div className="absolute right-[24%] top-[42%] h-2.5 w-2.5 rounded-full bg-[#c9a84c]"/><div className="absolute bottom-[25%] left-[46%] h-2.5 w-2.5 rounded-full bg-[#c9a84c]"/><div className="absolute inset-0 flex items-center justify-center"><Orbit size={72} strokeWidth={1} className="text-white/30"/></div></div></div></div></section>
  <section id="ai-mode" className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="border border-[#17231e]/10 bg-white/55 p-5 sm:p-7"><div className="flex items-center gap-3"><BrainCircuit className="text-[#2c5b48]"/><div><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#8a6e1e]">AI command center</p><h2 className="font-display text-3xl">What are we building?</h2></div></div><form className="mt-5 flex flex-col gap-2 sm:flex-row" onSubmit={e=>{e.preventDefault();if(prompt.trim())setSubmitted(true)}}><div className="flex flex-1 items-center border border-[#17231e]/15 bg-[#fbf8f0] px-3"><Search size={16}/><input value={prompt} onChange={e=>{setPrompt(e.target.value);setSubmitted(false)}} className="w-full bg-transparent px-3 py-3 text-sm outline-none" placeholder="Ask Bonds Studio to create, analyze, code, design, or navigate…"/></div><button className="inline-flex items-center justify-center gap-2 bg-[#1a2820] px-5 py-3 text-xs font-bold uppercase tracking-wider text-white"><Send size={15}/>Run</button></form>{submitted&&<p className="mt-3 text-xs text-[#2c5b48]">Command received. Connect an AI provider/tool execution layer to run this request.</p>}<div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="border border-[#17231e]/10 p-4"><BrainCircuit size={17}/><p className="mt-2 text-sm font-semibold">AI Assistant</p></div><button onClick={()=>navigate("/photo-engineer")} className="border border-[#17231e]/10 p-4 text-left"><ImagePlus size={17}/><p className="mt-2 text-sm font-semibold">AI Photo Engineer</p></button><div className="border border-[#17231e]/10 p-4"><Mic size={17}/><p className="mt-2 text-sm font-semibold">Voice control</p></div></div></div></section>
  <section id="photo-engineer" className="mx-auto max-w-7xl px-5 pb-8 sm:px-8"><div className="flex items-center justify-between border border-[#17231e]/10 bg-white/60 p-6"><div><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#8a6e1e]">AI image engineering</p><h2 className="mt-1 font-display text-3xl">Create and edit photos</h2></div><button onClick={()=>navigate("/photo-engineer")} className="bg-[#1a2820] px-4 py-2 text-xs font-semibold text-white">Open Photo Engineer</button></div></section>
  <section id="phone" className="mx-auto max-w-7xl px-5 pb-8 sm:px-8"><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-6"><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#8a6e1e]">Phone / Civic</p><h2 className="mt-1 font-display text-3xl">Contacts and geographic intelligence</h2><div className="mt-4 flex gap-2"><button onClick={()=>navigate("/phone")} className="border border-[#17231e]/15 px-4 py-2 text-xs font-semibold">Phone</button><button onClick={()=>navigate("/phone/earth")} className="bg-[#2c5b48] px-4 py-2 text-xs font-semibold text-white">Contact Earth</button></div></div></section>
  <section id="mobile-data" className="mx-auto max-w-7xl px-5 pb-8 sm:px-8"><div className="border border-[#17231e]/10 bg-white/60 p-6"><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#8a6e1e]">Mobile Data</p><h2 className="mt-1 font-display text-3xl">Cell service and device management</h2><p className="mt-2 text-sm text-[#657068]">Configure multiple mobile devices, SIM/eSIM status, network identifiers, and device build information.</p><button onClick={()=>navigate("/mobile-data")} className="mt-4 bg-[#1a2820] px-4 py-2 text-xs font-semibold text-white">Open Mobile Data</button></div></section>
  <section id="domains" className="mx-auto max-w-7xl px-5 pb-8 sm:px-8"><div className="border border-[#17231e]/10 bg-white/60 p-6"><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#8a6e1e]">Domains</p><h2 className="mt-1 font-display text-3xl">Domain registry</h2><p className="mt-2 text-sm text-[#657068]">Register and manage domains through the connected Bonds Registrar service.</p><button onClick={()=>navigate("/domains")} className="mt-4 bg-[#1a2820] px-4 py-2 text-xs font-semibold text-white">Open Domains</button></div></section>
  <section className="mx-auto grid max-w-7xl gap-4 px-5 pb-12 sm:grid-cols-2 lg:grid-cols-4 sm:px-8">{sections.filter(s=>!["orbit","ai-mode","phone","mobile-data","domains","photo-engineer"].includes(s.id)).map(({id,label,icon:Icon,description})=><article id={id} key={id} className="border border-[#17231e]/10 bg-white/45 p-5"><Icon size={19} className="text-[#2c5b48]"/><p className="mt-4 font-display text-xl">{label}</p><p className="mt-2 text-xs leading-5 text-[#657068]">{description}</p></article>)}</section>
  <section id="creative-projects" className="border-y border-[#17231e]/10 bg-[#eee8dc] px-5 py-10 sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#8a6e1e]">Creative projects</p><h2 className="mt-1 font-display text-3xl">Create in the format you need</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{["Document","Web","Image","Audio","Video"].map((name,i)=><div key={name} className="border border-[#17231e]/10 bg-[#fbf8f0] p-4"><span className="font-ledger text-[9px] text-[#8a6e1e]">0{i+1}</span><p className="mt-3 font-semibold">{name}</p></div>)}</div></div></section>
  <section id="ledger-projects" className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="border border-[#17231e]/10 bg-[#1a2820] p-6 text-white"><p className="font-ledger text-[10px] uppercase tracking-[.18em] text-[#c9a84c]">Ledger workspace</p><h2 className="mt-1 font-display text-3xl">Ledger projects remain separate from creative projects</h2></div></section></div>;
}

export default function App(){const[path,setPath]=useState(window.location.pathname);const[menuOpen,setMenuOpen]=useState(false);const navigate=(next:string)=>{window.history.pushState({},"",next);setPath(next);setMenuOpen(false);window.scrollTo(0,0)};useEffect(()=>{const onPop=()=>setPath(window.location.pathname);window.addEventListener("popstate",onPop);return()=>window.removeEventListener("popstate",onPop)},[]);if(path==="/phone/earth")return <><StudioHeader navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><ContactEarthPage/></>;if(path==="/phone")return <><StudioHeader navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><PhonePage onNavigate={navigate}/></>;if(path==="/mobile-data")return <><StudioHeader navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><MobileDataPage/></>;if(path==="/domains")return <><StudioHeader navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><DomainsPage/></>;if(path==="/photo-engineer")return <><StudioHeader navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><AIPhotoEngineerPage/></>;return <><StudioHeader navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen}/><HomeBody navigate={navigate}/></>}

function StudioHeader({navigate,menuOpen,setMenuOpen}:{navigate:(path:string)=>void;menuOpen:boolean;setMenuOpen:(value:boolean)=>void}){return <header className="sticky top-0 z-50 border-b border-white/10 bg-[#122019] text-white shadow-lg"><div className="mx-auto flex min-h-[70px] max-w-[1500px] items-center gap-3 px-4 sm:px-6"><button onClick={()=>navigate("/")} className="flex min-w-0 items-center gap-3 text-left"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-[#c9a84c]/40 bg-[#c9a84c]/10"><Orbit size={21} className="text-[#c9a84c]"/></span><span><span className="block font-display text-xl leading-none">Bonds Studio</span><span className="font-ledger text-[8px] uppercase tracking-[.2em] text-[#c9a84c]">AI · Creative · Workspace</span></span></button><div className="mx-auto hidden max-w-xl flex-1 md:block"><form onSubmit={e=>{e.preventDefault();document.getElementById("ai-mode")?.scrollIntoView({behavior:"smooth"})}} className="flex items-center border border-white/15 bg-white/5 px-3"><Search size={14}/><input className="w-full bg-transparent px-3 py-2.5 text-xs outline-none placeholder:text-white/40" placeholder="Ask Bonds Studio…"/><button className="px-2 text-[9px] font-bold uppercase tracking-wider text-[#c9a84c]">AI</button></form></div><button aria-label="Open Bonds Studio menu" onClick={()=>setMenuOpen(!menuOpen)} className="flex items-center gap-2 border border-white/15 px-3 py-2 text-xs font-semibold hover:bg-white/10"><Menu size={17}/><span className="hidden sm:inline">Menu</span>{menuOpen?<X size={14}/>:<ChevronDown size={14}/>}</button></div>{menuOpen&&<div className="border-t border-white/10 bg-[#17271f]"><nav className="mx-auto grid max-w-[1500px] grid-cols-1 gap-px bg-white/5 p-2 sm:grid-cols-2 lg:grid-cols-4">{sections.map(({id,label,icon:Icon,description})=><button key={id} onClick={()=>{setMenuOpen(false);if(id==="phone")navigate("/phone");else if(id==="mobile-data")navigate("/mobile-data");else if(id==="domains")navigate("/domains");else if(id==="photo-engineer")navigate("/photo-engineer");else{navigate("/");setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"}),0)}}} className="flex items-start gap-3 p-4 text-left hover:bg-white/10"><Icon size={18} className="mt-0.5 shrink-0 text-[#c9a84c]"/><span><strong className="block text-xs">{label}</strong><span className="mt-1 block text-[10px] leading-4 text-white/55">{description}</span></span></button>)}</nav></div>}</header>}
