CREATE TABLE `dnsRecords` (`id` int AUTO_INCREMENT NOT NULL, `zoneId` int NOT NULL, `name` varchar(253) NOT NULL, `type` enum('A','AAAA','CNAME','MX','NS','TXT','PTR','SRV','CAA','TLSA','CERT','SMIMEA','SSHFP','DNSKEY') NOT NULL, `value` varchar(2048) NOT NULL, `ttl` int NOT NULL DEFAULT 3600, `priority` int, `weight` int, `port` int, `flags` int, `tag` varchar(64), `order` int, `preference` int, `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `dnsRecords_id` PRIMARY KEY(`id`), KEY `dns_records_zone_name_type_idx` (`zoneId`,`name`,`type`));
--> statement-breakpoint
CREATE TABLE `dnsSettings` (`id` int AUTO_INCREMENT NOT NULL, `domainId` int NOT NULL, `authoritativeNameservers` text NOT NULL, `recursiveResolver` varchar(253), `defaultTtl` int NOT NULL DEFAULT 3600, `dnssecEnabled` int NOT NULL DEFAULT 0, `dnssecAlgorithm` varchar(64) DEFAULT 'ECDSAP256SHA256', `dnssecPublicKey` text, `dnssecKeyTag` int, `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `dnsSettings_id` PRIMARY KEY(`id`), CONSTRAINT `dnsSettings_domainId_unique` UNIQUE(`domainId`));
--> statement-breakpoint
CREATE TABLE `domains` (`id` int AUTO_INCREMENT NOT NULL, `ownerId` int NOT NULL, `name` varchar(253) NOT NULL, `tld` varchar(63) NOT NULL, `status` enum('active','expired','pending') NOT NULL DEFAULT 'pending', `registrar` varchar(160), `registrationDate` timestamp, `expirationDate` timestamp, `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `domains_id` PRIMARY KEY(`id`), CONSTRAINT `domains_name_unique` UNIQUE(`name`), CONSTRAINT `domains_owner_name_idx` UNIQUE(`ownerId`,`name`));
--> statement-breakpoint
CREATE TABLE `tlds` (`id` int AUTO_INCREMENT NOT NULL, `suffix` varchar(63) NOT NULL, `defaultRegistrationYears` int NOT NULL DEFAULT 1, `defaultTtl` int NOT NULL DEFAULT 3600, `active` int NOT NULL DEFAULT 1, CONSTRAINT `tlds_id` PRIMARY KEY(`id`), CONSTRAINT `tlds_suffix_unique` UNIQUE(`suffix`));
--> statement-breakpoint
CREATE TABLE `zones` (`id` int AUTO_INCREMENT NOT NULL, `domainId` int NOT NULL, `primaryNameserver` varchar(253) NOT NULL DEFAULT 'ns1.example.net.', `adminEmail` varchar(253) NOT NULL DEFAULT 'hostmaster.example.net.', `serial` int NOT NULL DEFAULT 2026010101, `refresh` int NOT NULL DEFAULT 3600, `retry` int NOT NULL DEFAULT 600, `expire` int NOT NULL DEFAULT 604800, `minimumTtl` int NOT NULL DEFAULT 300, `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `zones_id` PRIMARY KEY(`id`), CONSTRAINT `zones_domainId_unique` UNIQUE(`domainId`));
INSERT INTO `tlds` (`suffix`,`defaultRegistrationYears`,`defaultTtl`,`active`) VALUES ('.com',1,3600,1),('.net',1,3600,1),('.org',1,3600,1),('.io',1,3600,1),('.dev',1,3600,1),('.ai',1,3600,1),('.bonds',1,3600,1);
