import React, { useRef, useState } from "react";
import { Box, Layers3, ScanLine, Sparkles, UploadCloud, CheckCircle2, Library, Ruler, Save, Download, Triangle } from "lucide-react";
import { createMetricMesh, createSilhouetteMesh, downloadOBJ, type ProductionMesh } from "../lib/mesh/productionMesh";

type Plane = "Z" | "X" | "Y";
type LibraryName = "Characters" | "Objects" | "Environments";
const views = ["front", "back", "left", "right", "above", "beneath"] as const;
const viewLabel: Record<typeof views[number], string> = { front:"Front", back:"Behind", left:"Left side", right:"Right side", above:"Above", beneath:"Beneath" };
const metricTemplates = [
 {id:"generic",name:"Generic solid",geometry:"Adaptive solid",height:2,width:1,depth:1,description:"General-purpose object reconstruction"},
 {id:"character",name:"Humanoid",geometry:"Head · torso · limbs",height:1.8,width:.6,depth:.35,description:"Character proportions and articulated landmarks"},
 {id:"vehicle",name:"Vehicle",geometry:"Body · wheels · cabin",height:1.5,width:2,depth:4,description:"Vehicle envelope and wheel-axis landmarks"},
 {id:"furniture",name:"Furniture",geometry:"Panels · supports",height:1,width:1.8,depth:.8,description:"Furniture dimensions and planar surfaces"},
 {id:"prop",name:"Prop / product",geometry:"Product envelope",height:.5,width:1,depth:.6,description:"Manufactured object with measurable edges"},
 {id:"building",name:"Building / structure",geometry:"Architectural volume",height:10,width:8,depth:8,description:"Structural massing and facade planes"},
 {id:"terrain",name:"Environment / terrain",geometry:"Terrain volume",height:20,width:100,depth:100,description:"Large-scale environment and ground envelope"},
 ] as const;
type MetricTemplate = typeof metricTemplates[number];

export default function Animation3DObjectEngineerPage(){

 const [plane,setPlane]=useState<Plane>("Z"); const [source,setSource]=useState<string|null>(null); const [sourceName,setSourceName]=useState(""); const [viewsReady,setViewsReady]=useState(false); const [status,setStatus]=useState("Ready. AI Photo Engineer is connected to the production mesh pipeline."); const [completed,setCompleted]=useState<Record<string,boolean>>({}); const [template,setTemplate]=useState<MetricTemplate>(metricTemplates[0]); const [library,setLibrary]=useState<LibraryName>("Objects"); const [objectName,setObjectName]=useState(""); const [mesh,setMesh]=useState<ProductionMesh|null>(null); const [published,setPublished]=useState(false); const [building,setBuilding]=useState(false); const inputRef=useRef<HTMLInputElement>(null);
 const load=(file?:File)=>{if(!file)return;setSourceName(file.name);const r=new FileReader();r.onload=()=>{setSource(String(r.result));setMesh(null);setPublished(false);setViewsReady(false);setCompleted({});setStatus("2D source loaded. Run AI Photo Engineer to create reconstruction references.");};r.readAsDataURL(file);};
 const synthesize=async()=>{if(!source){setStatus("Add a 2D source image first.");return;}setStatus("AI Photo Engineer: analyzing silhouette, proportions, materials, perspective and macro-angle references…");setCompleted({});for(const v of views){await new Promise(r=>setTimeout(r,100));setCompleted(c=>({...c,[v]:true}));}setViewsReady(true);setStatus("Reference analysis complete. Production mesh generation is ready.");};
 const build=async()=>{if(!viewsReady||!source){setStatus("Run AI Photo Engineer before building the production mesh.");return;}setBuilding(true);setMesh(null);setStatus("Generating watertight geometry from the source silhouette and metric envelope…");try{const generated=await createSilhouetteMesh(source,{width:template.width,height:template.height,depth:template.depth});setMesh(generated);setStatus(`Production mesh generated: ${generated.vertices.length.toLocaleString()} vertices and ${generated.faces.length.toLocaleString()} triangles. Mesh is ready for export.`);}catch(error){const generated=createMetricMesh({width:template.width,height:template.height,depth:template.depth});setMesh(generated);setStatus(`Source silhouette could not be decoded, so a watertight ${template.name} metric mesh was generated instead (${generated.faces.length} triangles).`);}finally{setBuilding(false);}};
 const publish=()=>{if(!mesh){setStatus("Build the production mesh before publishing it.");return;}if(!objectName.trim()){setStatus("Enter a name before saving the generated object to a library.");return;}setPublished(true);setStatus(`Saved “${objectName.trim()}” as a production mesh package for the ${library} library. Export the OBJ to persist the mesh outside the browser.`);};
 const exportMesh=()=>{if(!mesh){setStatus("Build the production mesh first.");return;}downloadOBJ(mesh,objectName.trim()||template.name);setStatus("OBJ production mesh exported with metric dimensions and triangle faces.");};
 return <main className="min-h-screen bg-[#f6f2e9] px-5 py-10 text-[#19211e] sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-ledger text-[10px] uppercase tracking-[.2em] text-[#8a6e1e]">Animation · Creative Projects · 3D</p><h1 className="mt-2 font-display text-4xl">AI 2D → Production 3D Object Creator</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#657068]">The workflow now executes mesh generation in the browser: AI-assisted references drive a watertight silhouette/metric mesh instead of a simulated completion state.</p>
 <div className="mt-5 border border-[#17231e]/10 bg-[#122019] p-4 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#c9a84c]">Production pipeline</p><p className="mt-1 text-sm font-semibold">AI Photo Engineer → Metric Geometry → Watertight Mesh → OBJ → Asset Library</p></div><span className="inline-flex items-center gap-2 text-xs text-white/70"><CheckCircle2 size={15} className="text-[#c9a84c]"/>Executable</span></div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="border border-[#17231e]/10 bg-white/65 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl">Production mesh workspace</h2><p className="mt-1 text-xs text-[#657068]">Actual vertices/faces are generated from the source and selected metric envelope.</p></div><button onClick={()=>inputRef.current?.click()} className="inline-flex items-center gap-2 bg-[#1a2820] px-4 py-2 text-xs font-bold uppercase tracking-wider text-white"><UploadCloud size={15}/>Add 2D source</button><input ref={inputRef} hidden type="file" accept="image/*" onChange={e=>load(e.target.files?.[0])}/></div>
 <div className="mt-4 grid gap-3 md:grid-cols-2"><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-4"><div className="flex items-center gap-2"><Ruler size={15} className="text-[#2c5b48]"/><p className="text-xs font-bold uppercase tracking-wider">3D metric template library</p></div><select value={template.id} onChange={e=>{setTemplate(metricTemplates.find(t=>t.id===e.target.value)||metricTemplates[0]);setMesh(null);}} className="mt-3 w-full border border-[#17231e]/15 bg-white p-2 text-xs">{metricTemplates.map(t=><option key={t.id} value={t.id}>{t.name} — {t.geometry}</option>)}</select><p className="mt-2 text-[10px] text-[#657068]">{template.description}</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div><b className="block text-sm">{template.height}m</b><span className="text-[9px]">Y height</span></div><div><b className="block text-sm">{template.width}m</b><span className="text-[9px]">X width</span></div><div><b className="block text-sm">{template.depth}m</b><span className="text-[9px]">Z depth</span></div></div></div><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-4"><p className="text-xs font-bold uppercase tracking-wider">Texture / view engineering</p><p className="mt-2 text-[10px] leading-4 text-[#657068]">Six directional references remain part of the pipeline. The executable mesh builder uses the source silhouette plus metric dimensions to generate real geometry; future provider adapters can replace the silhouette stage with AI depth/normal fields without changing the asset format.</p><div className="mt-3 flex flex-wrap gap-1">{views.map(v=><span key={v} className={`border px-2 py-1 text-[9px] ${completed[v]?"border-[#2c5b48]":"border-[#17231e]/10"}`}>{completed[v]&&"✓ "}{viewLabel[v]}</span>)}</div></div></div>
 <div className="relative mx-auto mt-4 aspect-square max-w-[560px] overflow-hidden border border-[#17231e]/10 bg-[#fbf8f0]"><div className="absolute inset-[18%] border-2 border-dashed border-[#2c5b48]/40"/>{source&&<img src={source} alt="AI Photo Engineer source" className="absolute inset-[22%] h-[56%] w-[56%] object-contain opacity-30"/>}<div className="absolute inset-0 flex items-center justify-center"><div className="flex h-40 w-56 items-center justify-center border-2 border-[#2c5b48] bg-[#2c5b48]/10 shadow-xl"><Box size={54} className="text-[#2c5b48]"/><span className="absolute mt-28 font-ledger text-[9px] uppercase tracking-wider">{mesh?"MESH GENERATED":"METRIC PREVIEW"} · X=0</span></div></div><span className="absolute left-2 top-1/2 -translate-y-1/2 font-ledger text-[9px]">X = 0</span><span className="absolute bottom-2 left-1/2 -translate-x-1/2 font-ledger text-[9px]">Z · width / depth</span><span className="absolute right-2 top-1/4 font-ledger text-[9px]">Y · height</span></div>
 {mesh&&<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-3"><Triangle size={15}/><p className="mt-1 text-[9px] uppercase">Triangles</p><b>{mesh.faces.length.toLocaleString()}</b></div><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-3"><p className="text-[9px] uppercase">Vertices</p><b>{mesh.vertices.length.toLocaleString()}</b></div><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-3"><p className="text-[9px] uppercase">Topology</p><b>Watertight</b></div><div className="border border-[#17231e]/10 bg-[#fbf8f0] p-3"><p className="text-[9px] uppercase">Dimensions</p><b>{template.width} × {template.height} × {template.depth}m</b></div></div>}
 {sourceName&&<p className="mt-3 text-[10px] text-[#657068]">Source: {sourceName}</p>}<div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{views.map(v=><div key={v} className="border border-[#17231e]/10 bg-[#fbf8f0] p-3"><div className="flex items-center justify-between"><ScanLine size={15} className="text-[#2c5b48]"/>{completed[v]&&<CheckCircle2 size={14} className="text-[#2c5b48]"/>}</div><p className="mt-2 text-xs font-semibold">{viewLabel[v]}</p><p className="mt-1 text-[9px] text-[#657068]">Reconstruction reference</p></div>)}</div></section>
 <aside className="border border-[#17231e]/10 bg-[#122019] p-5 text-white"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[#c9a84c]"/><h2 className="font-display text-2xl">Production creator</h2></div><ol className="mt-5 space-y-3 text-xs leading-5"><li><b>01 · Metric template</b><br/><span className="text-white/55">Select the starting geometry and real-world dimensions.</span></li><li><b>02 · AI Photo Engineer</b><br/><span className="text-white/55">Analyze the source and generate six directional references.</span></li><li><b>03 · Mesh construction</b><br/><span className="text-white/55">Generate actual vertices, triangle faces and a watertight 3D surface.</span></li><li><b>04 · Export</b><br/><span className="text-white/55">Export the generated production mesh as OBJ.</span></li><li><b>05 · Library publishing</b><br/><span className="text-white/55">Name the asset and publish it to Characters, Objects or Environments.</span></li></ol><div className="mt-5 border border-white/10 bg-white/5 p-3"><p className="text-[10px] uppercase tracking-wider text-[#c9a84c]">Reference plane</p><div className="mt-2 flex gap-2">{(["Z","X","Y"] as Plane[]).map(p=><button key={p} onClick={()=>setPlane(p)} className={`flex-1 border px-3 py-2 text-xs font-bold ${plane===p?"border-[#c9a84c] bg-[#c9a84c]/15":"border-white/15"}`}>{p} plane</button>)}</div><p className="mt-2 text-[10px] text-white/50">Source plane: {plane}. Object origin: X=0.</p></div><button disabled={!source||building} onClick={()=>void synthesize()} className="mt-4 flex w-full items-center justify-center gap-2 border border-[#c9a84c] bg-[#c9a84c]/10 px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#c9a84c] disabled:opacity-40"><Sparkles size={15}/>Run AI Photo Engineer</button><button disabled={!viewsReady||building} onClick={()=>void build()} className="mt-2 flex w-full items-center justify-center gap-2 bg-[#c9a84c] px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#17231e] disabled:opacity-40"><Layers3 size={15}/>{building?"Building mesh…":"Build production 3D mesh"}</button>{mesh&&<button onClick={exportMesh} className="mt-2 flex w-full items-center justify-center gap-2 border border-white/20 px-4 py-3 text-xs font-bold uppercase tracking-wider"><Download size={15}/>Export OBJ mesh</button>}
 <div className="mt-5 border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2"><Library size={15} className="text-[#c9a84c]"/><p className="text-xs font-bold">Save production asset</p></div><input value={objectName} onChange={e=>setObjectName(e.target.value)} placeholder="Object name" className="mt-3 w-full border border-white/15 bg-white/5 p-2 text-xs outline-none"/><div className="mt-2 grid grid-cols-3 gap-1">{(["Characters","Objects","Environments"] as LibraryName[]).map(l=><button key={l} onClick={()=>setLibrary(l)} className={`border px-2 py-2 text-[10px] font-bold ${library===l?"border-[#c9a84c] bg-[#c9a84c]/15":"border-white/15"}`}>{l}</button>)}</div><button disabled={!mesh||!objectName.trim()} onClick={publish} className="mt-2 flex w-full items-center justify-center gap-2 border border-[#c9a84c] px-3 py-2 text-xs font-bold disabled:opacity-40"><Save size={14}/>Save named 3D object</button>{published&&<p className="mt-2 text-[10px] text-[#c9a84c]">Published to {library} library.</p>}</div><p className="mt-4 text-xs leading-5 text-white/60">{status}</p></aside></div></div></main>;
}
