import React, { useState } from "react";
import { Box, Layers3, ScanLine, Sparkles } from "lucide-react";

type Plane = "Z" | "X" | "Y";
const views = ["front", "back", "left", "right", "above", "beneath"] as const;

export default function Animation3DObjectEngineerPage(){
 const [plane,setPlane]=useState<Plane>("Z"); const [status,setStatus]=useState("Ready to convert a 2D image into a six-view 3D reconstruction.");
 const build=()=>setStatus("Reconstruction plan created: image on Z plane → X=0 center plane → Y=height → Z=width → side, top, and underside views synthesized into a volumetric mesh.");
 return <main className="min-h-screen bg-[#f6f2e9] px-5 py-10 text-[#19211e] sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-ledger text-[10px] uppercase tracking-[.2em] text-[#8a6e1e]">Animation · 3D Object Engineering</p><h1 className="mt-2 font-display text-4xl">AI 2D → 3D Object Reconstruction</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#657068]">Uses the AI Photo Engineer as the image-generation and view-synthesis stage, then reconstructs the object across spatial planes and six directional views.</p>
 <div className="mt-7 grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="border border-[#17231e]/10 bg-white/65 p-5"><div className="relative mx-auto aspect-square max-w-[560px] overflow-hidden border border-[#17231e]/10 bg-[#fbf8f0]"><div className="absolute inset-[18%] border-2 border-dashed border-[#2c5b48]/40"/><div className="absolute left-1/2 top-[18%] h-[64%] w-px bg-[#8a6e1e]/50"/><div className="absolute left-[18%] top-1/2 h-px w-[64%] bg-[#8a6e1e]/50"/><div className="absolute inset-0 flex items-center justify-center"><div className="flex h-40 w-56 items-center justify-center border-2 border-[#2c5b48] bg-[#2c5b48]/10 shadow-xl"><Box size={54} className="text-[#2c5b48]"/><span className="absolute mt-28 font-ledger text-[9px] uppercase tracking-wider">Object volume</span></div></div><span className="absolute left-2 top-1/2 -translate-y-1/2 font-ledger text-[9px]">X</span><span className="absolute bottom-2 left-1/2 -translate-x-1/2 font-ledger text-[9px]">Z · width</span><span className="absolute right-2 top-1/4 font-ledger text-[9px]">Y · height</span></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{views.map(v=><div key={v} className="border border-[#17231e]/10 bg-[#fbf8f0] p-3"><ScanLine size={15} className="text-[#2c5b48]"/><p className="mt-2 text-xs font-semibold capitalize">{v}</p><p className="mt-1 text-[9px] text-[#657068]">AI reconstructed texture</p></div>)}</div></section>
 <aside className="border border-[#17231e]/10 bg-[#122019] p-5 text-white"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[#c9a84c]"/><h2 className="font-display text-2xl">Reconstruction pipeline</h2></div><ol className="mt-5 space-y-3 text-xs leading-5"><li><b>01 · AI Photo Engineer</b><br/><span className="text-white/55">Create/analyze the source image and synthesize missing object views.</span></li><li><b>02 · Z-plane image</b><br/><span className="text-white/55">Place the generated source representation on the Z plane as the reference projection.</span></li><li><b>03 · X-plane anchor</b><br/><span className="text-white/55">Center the reconstruction at X = 0.</span></li><li><b>04 · Spatial dimensions</b><br/><span className="text-white/55">Y represents object height; Z represents object width in the configured reconstruction coordinate system.</span></li><li><b>05 · Six-view reconstruction</b><br/><span className="text-white/55">Front, back, left, right, above, and beneath views are generated, aligned, and fused.</span></li><li><b>06 · Mesh + textures</b><br/><span className="text-white/55">Depth, silhouette, materials, UVs, and view textures are prepared for the 3D animation module.</span></li></ol><div className="mt-5 border border-white/10 bg-white/5 p-3"><p className="text-[10px] uppercase tracking-wider text-[#c9a84c]">Reference plane</p><div className="mt-2 flex gap-2">{(["Z","X","Y"] as Plane[]).map(p=><button key={p} onClick={()=>setPlane(p)} className={`flex-1 border px-3 py-2 text-xs font-bold ${plane===p?"border-[#c9a84c] bg-[#c9a84c]/15":"border-white/15"}`}>{p} plane</button>)}</div><p className="mt-2 text-[10px] text-white/50">Current source plane: {plane}. Object origin: X=0.</p></div><button onClick={build} className="mt-4 flex w-full items-center justify-center gap-2 bg-[#c9a84c] px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#17231e]"><Layers3 size={15}/>Build 3D reconstruction</button><p className="mt-4 text-xs leading-5 text-white/60">{status}</p></aside></div></div></main>;
}
