import React, { useEffect, useState } from "react";
import { BookUser, MapPin, Phone as PhoneIcon } from "lucide-react";
export type PhoneContact = { id: number; name: string; phoneNumber: string; email?: string | null; address?: string | null; notes?: string | null; latitude?: string | number | null; longitude?: string | number | null };
export const CONTACTS_KEY = "bondsStudio.phoneContacts";
export function readPhoneContacts(): PhoneContact[] { try { const value = JSON.parse(localStorage.getItem(CONTACTS_KEY) || "[]"); return Array.isArray(value) ? value : []; } catch { return []; } }
export default function PhonePage({ onNavigate }: { onNavigate: (path: string) => void }) {
 const [contacts,setContacts]=useState<PhoneContact[]>([]); useEffect(()=>{const load=()=>setContacts(readPhoneContacts());load();window.addEventListener("storage",load);return()=>window.removeEventListener("storage",load)},[]);
 return <div style={{maxWidth:1100,margin:"0 auto",padding:28}}><header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",flexWrap:"wrap",borderBottom:"1px solid #d9d3c7",paddingBottom:20}}><div><div style={{display:"flex",gap:12,alignItems:"center"}}><PhoneIcon/><h1 style={{fontSize:36,margin:0}}>Phone</h1></div><p style={{color:"#657068"}}>Workspace contacts and their stored addresses.</p></div><button onClick={()=>onNavigate("/phone/earth")} style={{display:"flex",gap:8,alignItems:"center",background:"#2c5b48",color:"white",border:0,padding:"12px 16px",cursor:"pointer"}}><MapPin size={17}/>Contact Earth</button></header><section style={{marginTop:24,background:"#fbf8f0",border:"1px solid #d9d3c7"}}><div style={{padding:"14px 18px",borderBottom:"1px solid #d9d3c7",display:"flex",gap:8,alignItems:"center"}}><BookUser size={17}/><strong>Workspace contacts</strong></div>{!contacts.length?<p style={{padding:24,color:"#657068"}}>No contacts are stored in this browser yet. Contacts with addresses will appear on Earth automatically.</p>:contacts.map(c=><div key={c.id} style={{padding:"16px 18px",borderBottom:"1px solid #e4dfd6",display:"flex",justifyContent:"space-between",gap:16}}><div><strong>{c.name}</strong><div style={{fontSize:13,color:"#657068"}}>{c.phoneNumber}</div>{c.address&&<div style={{fontSize:12,color:"#8a6e1e",marginTop:4}}>{c.address}</div>}</div>{c.address&&<button onClick={()=>onNavigate("/phone/earth")} style={{border:0,background:"transparent",color:"#2c5b48",cursor:"pointer"}}>View on Earth</button>}</div>)}</section></div>;
}
